name: Publish package

on:
  push:
    tags:
      - "v*"
      - "!v*-alpha"
      - "!v*-beta"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Set Node version
        uses: actions/setup-node@main
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          check-latest: true

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          yarn publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
