name: Test and Lint

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"

jobs:
  test-n-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Check formats
        run: yarn check-format

      - name: Test
        run: yarn test
