name: Test and Lint

on:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - "*"
    tags-ignore:
      - "*"

jobs:
  test-n-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Set Node version
        uses: actions/setup-node@main
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          check-latest: true

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Check formats
        run: yarn check-format

      - name: Test
        run: yarn test
